/**
 * src/types/tb — handwritten authoritative wire types for the TB REST/WS API.
 *
 * Layers:
 *   ./openapi/   generated by `npm run openapi:gen` from ui-antd/api/tb-openapi.json
 *                (raw material, never hand-edited, consulted for cross-checking only)
 *   ./*.ts       handwritten types app code actually consumes
 *
 * Conventions:
 *   - All timestamps are ms-since-epoch numbers (EpochMillis alias).
 *   - Entity references are `{ entityType, id }`; typed via EntityIdOf<E>.
 *   - Page indexes are 0-based on the server.
 */

export * from './alarm';
export * from './customer';
export * from './device';
export * from './entity';
export * from './page';
export * from './telemetry';
export * from './user';
