/**
 * dashboard filter keyFilters → wire KeyFilter conversion (W4 fix).
 *
 * Live defect (2026-09-03, gateways system dashboard): the dashboard JSON
 * stores each keyFilter's predicate list in the ui-ngx FRONTEND shape —
 * `predicates: [{ keyFilterPredicate: {...}, userInfo: {...} }]` — while the
 * WS wire contract (TbWebSocketHandler → Jackson KeyFilter) expects a single
 * flattened `predicate` and rejects the frontend shape with close 1007
 * "The given string value cannot be transformed to Json object". The ws
 * manager then misreads that close as an auth failure and the unauthorized
 * exit logs the user out. Repro: /entities/gateways on tenant@thingsboard.org.
 */

import { describe, expect, it } from 'vitest';
import { toWireKeyFilters } from './key-filters';

describe('toWireKeyFilters', () => {
  it('unwraps the dashboard (ui-ngx) predicate shape to the wire KeyFilter', () => {
    const dashboardShape = [
      {
        key: { type: 'ENTITY_FIELD', key: 'additionalInfo' },
        valueType: 'STRING',
        predicates: [
          {
            keyFilterPredicate: {
              operation: 'CONTAINS',
              value: { defaultValue: '"gateway":true', dynamicValue: null },
              ignoreCase: false,
              type: 'STRING',
            },
            userInfo: {
              editable: true,
              label: '',
              autogeneratedLabel: true,
              order: 0,
            },
          },
        ],
      },
    ];
    expect(toWireKeyFilters(dashboardShape)).toEqual([
      {
        key: { type: 'ENTITY_FIELD', key: 'additionalInfo' },
        valueType: 'STRING',
        predicate: {
          operation: 'CONTAINS',
          value: { defaultValue: '"gateway":true' },
          ignoreCase: false,
          type: 'STRING',
        },
      },
    ]);
  });

  it('keeps an already-wire-shaped keyFilter (predicate field) as-is', () => {
    const wireShape = [
      {
        key: { type: 'TIME_SERIES', key: 'fw_state' },
        valueType: 'JSON',
        predicate: {
          operation: 'EXISTS',
          value: { defaultValue: null },
          type: 'EXISTS',
        },
      },
    ];
    expect(toWireKeyFilters(wireShape)).toEqual(wireShape);
  });

  it('passes the firmware html_value_card fixture (key-only entries) through', () => {
    const keyOnly = [{ key: { type: 'TIME_SERIES', key: 'fw_state' } }];
    expect(toWireKeyFilters(keyOnly)).toEqual([
      { key: { type: 'TIME_SERIES', key: 'fw_state' } },
    ]);
  });

  it('flattens COMPOSITE predicates recursively (complex filters)', () => {
    const composite = [
      {
        key: { type: 'ATTRIBUTE', key: 'active' },
        valueType: 'BOOLEAN',
        predicates: [
          {
            keyFilterPredicate: {
              type: 'COMPLEX',
              operation: 'OR',
              predicates: [
                {
                  keyFilterPredicate: {
                    operation: 'EQUAL',
                    value: { defaultValue: false },
                    type: 'BOOLEAN',
                  },
                  userInfo: { order: 0 },
                },
              ],
              userInfo: { order: 1 },
            },
          },
        ],
      },
    ];
    expect(toWireKeyFilters(composite)).toEqual([
      {
        key: { type: 'ATTRIBUTE', key: 'active' },
        valueType: 'BOOLEAN',
        predicate: {
          type: 'COMPLEX',
          operation: 'OR',
          predicates: [
            {
              operation: 'EQUAL',
              value: { defaultValue: false },
              type: 'BOOLEAN',
            },
          ],
        },
      },
    ]);
  });

  it('uses the first predicate and omits the field when none exists', () => {
    const two = [
      {
        key: { type: 'ATTRIBUTE', key: 'active' },
        valueType: 'BOOLEAN',
        predicates: [
          {
            keyFilterPredicate: {
              operation: 'EQUAL',
              value: { defaultValue: true },
              type: 'BOOLEAN',
            },
          },
          {
            keyFilterPredicate: {
              operation: 'EQUAL',
              value: { defaultValue: false },
              type: 'BOOLEAN',
            },
          },
        ],
      },
      { key: { type: 'ATTRIBUTE', key: 'x' }, valueType: 'STRING' },
    ];
    expect(toWireKeyFilters(two)).toEqual([
      {
        key: { type: 'ATTRIBUTE', key: 'active' },
        valueType: 'BOOLEAN',
        predicate: {
          operation: 'EQUAL',
          value: { defaultValue: true },
          type: 'BOOLEAN',
        },
      },
      { key: { type: 'ATTRIBUTE', key: 'x' }, valueType: 'STRING' },
    ]);
  });

  it('returns an empty array for empty input and preserves value payloads', () => {
    expect(toWireKeyFilters([])).toEqual([]);
    const withDynamic = [
      {
        key: { type: 'ATTRIBUTE', key: 'connectorType' },
        valueType: 'STRING',
        predicates: [
          {
            keyFilterPredicate: {
              operation: 'EQUAL',
              value: {
                defaultValue: 'mqtt',
                dynamicValue: {
                  sourceType: 'CURRENT_DEVICE',
                  sourceAttribute: 'type',
                },
              },
              ignoreCase: true,
              type: 'STRING',
            },
          },
        ],
      },
    ];
    expect(toWireKeyFilters(withDynamic)[0].predicate).toEqual({
      operation: 'EQUAL',
      value: {
        defaultValue: 'mqtt',
        dynamicValue: {
          sourceType: 'CURRENT_DEVICE',
          sourceAttribute: 'type',
        },
      },
      ignoreCase: true,
      type: 'STRING',
    });
  });
});
